---
title: "MAP Project"
author: "Simon Gabay"
date: "`r Sys.Date()`"
output:
  html_notebook:
  number_sections: yes
toc: yes
toc_float: yes
---
  
```{r, setup, fig.show=hold, fig.margin=TRUE}
if(!require("knitr")){
  install.packages("knitr")
  library(knitr)
}
if(!require("magrittr")){
  install.packages("magrittr")
  library(magrittr)
}
if(!require("leaflet")){
  install.packages("leaflet")
  library(leaflet)
}
if(!require("htmlwidgets")){
  install.packages("htmlwidgets")
  library(htmlwidgets)
}
knitr::opts_chunk$set(echo = TRUE, fig.width=20)
```

Set your working directory

```{r, results='hide'}
setwd("~/GitHub/MAP/MAP_R")
```

Load your data

```{r, results='hide'}
#import de csv
MAP  <- read.csv("MAP.csv")
```

Have a quick look at the data

```{r}
View(MAP)
df <- data.frame(title=MAP$title,
                 place=MAP$place,
                 lat=MAP$lat,
                 long=MAP$lng,
                 URL=MAP$URL)
#df
```

Map it!

```{r}
map<-leaflet()%>%
## On ajoute un fond de carte
addProviderTiles(providers$Esri.NatGeoWorldMap)%>% 
  
  # Je définis le point central de ma carte
  setView(lng = 0, 
          lat = 47, 
          zoom = 6 )%>%
  
  # J'ajoute les points issues des pièces de Boyer
  addCircleMarkers(lng = MAP$lng, 
                   lat = MAP$lat,
                   popup=MAP$URL
                   #popup = paste(sep="",
                   #             "<i>",
                   #              MAP$title,"</i>, ",
                   #               MAP$place,
                   #              " [<a href='",MAP$URL,"' target=\"_blank\">Voir la fiche</a>]"
                   #              )
                   )%>%

addLegend("topright", 
              colors = c("trasparent"),
              labels=c("Simon Gabay - simon.gabay@unige.ch"),
              title="MAP - Middle Ages & Performances")
saveWidget(map, file="index.html")
```