---
title: "LeReMed Project"
author: "Simon Gabay"
date: "`r Sys.Date()`"
output:
  html_notebook:
  number_sections: yes
toc: yes
toc_float: yes
---
  
```{r, setup, fig.show=hold, fig.margin=TRUE}
if(!require("knitr")){
  install.packages("knitr")
  library(knitr)
}
if(!require("magrittr")){
  install.packages("magrittr")
  library(magrittr)
}
if(!require("leaflet")){
  install.packages("leaflet")
  library(leaflet)
}
if(!require("htmlwidgets")){
  install.packages("htmlwidgets")
  library(htmlwidgets)
}
if(!require("htmltools")){
  install.packages("htmltools")
  library(htmltools)
}
knitr::opts_chunk$set(echo = TRUE, fig.width=20)
```

Set your working directory

```{r, results='hide'}
setwd("~/MAP/MAP_R")
```

Load your data

```{r, results='hide'}
#import de csv
MAP12  <- read.csv("1200.csv")
MAP13  <- read.csv("1300.csv")
MAP14  <- read.csv("1400.csv")
MAP15  <- read.csv("1500.csv")
MAP16  <- read.csv("1600.csv")
```

Have a quick look at the data

```{r}
View(MAP12)
View(MAP13)
View(MAP14)
View(MAP15)
View(MAP16)
```

Map it!

```{r}
map<-leaflet()%>%
## On ajoute un fond de carte
addProviderTiles(providers$Esri.NatGeoWorldMap)%>%
  addMiniMap(
    tiles = providers$Esri.WorldStreetMap,
    toggleDisplay = TRUE)%>%
  
  # Je définis le point central de ma carte
  setView(lng = 2, 
          lat = 47, 
          zoom = 6 )%>%

  
  addEasyButton(easyButton(
    icon="fa-globe", title="Zoom to Level 1",
    onClick=JS("function(btn, map){ map.setZoom(6); }"))) %>%
  
  # J'ajoute les points issues des pièces siècle par siècle
 addCircleMarkers(data = MAP12, 
                   lng = MAP12$lng, 
                   lat = MAP12$lat,
                   color = MAP12$color,
                   fillOpacity = 0.5,
                   group = "XIIIeme",
                   popup=MAP12$list
                   )%>%
  
 addCircleMarkers(data = MAP13, 
                   lng = MAP13$lng, 
                   lat = MAP13$lat,
                   color = MAP13$color,
                   fillOpacity = 0.5,
                   group = "XIVeme",
                   popup=MAP13$list
                   )%>%

  addCircleMarkers(data = MAP14, 
                   lng = MAP14$lng, 
                   lat = MAP14$lat,
                   color = MAP14$color,
                   fillOpacity = 0.5,
                   group = "XVeme",
                   popup=MAP14$list
                   )%>%
  
 addCircleMarkers(data = MAP15, 
                   lng = MAP15$lng, 
                   lat = MAP15$lat,
                   color = MAP15$color,
                   fillOpacity = 0.5,
                   group = "XVIeme",
                   popup=MAP15$list
                   )%>%
  
 addCircleMarkers(data = MAP16, 
                   lng = MAP16$lng, 
                   lat = MAP16$lat,
                   color = MAP16$color,
                   fillOpacity = 0.5,
                   group = "XVIIeme",
                   popup=MAP16$list
                   )%>%
  
  
    # J'ajoute les points issues des pièces de Boyer
#  addCircleMarkers(lng = MAP$lng, 
#                   lat = MAP$lat,
#                   color = MAP$color,
#                   popup=MAP$list
#                   )%>%

   # Add a legend that combines icon markers layers and heatmap layers
    addLegend(position = "bottomleft", 
              labels = c("XIIIeme",
                         "XIVeme",
                         "XVeme",
                         "XVIeme",
                         "XVIIeme"), 
              
              colors = c("white", 
                         "green", 
                         "red", 
                         "blue",
                         "black"),
              
              title = "Toponymes par siècles:") %>%
  
  
addLegend("topright", 
              colors = c("trasparent","trasparent", "transparent"),
              labels=c("Contact: <a href='mailto:simon.gabay@unige.ch' target='_blank'>simon.gabay@unige.ch</a>",
                       "Code source: <a href='https://github.com/LeReMed' target='_blank'>https://github.com/LeReMed</a>",
                       "<a href='https://leremed.huma-num.fr' target='_blank'>Retour à l'application web</a>"),
              title="LeReMed - Les Représentations Médiévales") %>%

  addLayersControl(overlayGroups = c("XIIIeme",
                                     "XIVeme",
                                     "XVeme",
                                     "XVIeme",
                                     "XVIIeme"),
                   options = layersControlOptions(collapsed = FALSE)
  )
saveWidget(map, file="map.html")
```
```